name: domain
description: Shopping List app models
version: 0.0.1
author: Emanuel López
homepage: http://www.emanuellopez.com.ar

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.9.0
