name: app
description: Shopping List app
publish_to: 'none'
version: 0.0.1
homepage: http://www.emanuellopez.com.ar

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_utils:
    path: ../../dart-utils
  injector: ^2.0.0
  presentation:
    path: ../presentation
  flutter_qr_bar_scanner: ^2.0.0
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
