name: app
description: Shopping List app
publish_to: 'none'
version: 0.0.1
author: Emanuel López
homepage: http://www.emanuellopez.com.ar

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  injector: ^2.0.0
  presentation:
    path: ../presentation

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
